---
- name: Ensure GNOME Shell extension directories exist
  ansible.builtin.file:
    path: "/home/{{ item.0 }}/{{ item.1 }}"
    state: directory
    owner: "{{ item.0 }}"
    group: "{{ item.0 }}"
    mode: "0755"
  loop: "{{ gnome_desktop_users | product([gnome_shell_extension_cache_directory, gnome_shell_extension_directory]) | list }}"
  loop_control:
    label: "{{ item.0 }} {{ item.1 }}"

- name: Install GNOME Shell extensions
  ansible.builtin.include_tasks: extension.yml
  vars:
    gnome_shell_extension_user: "{{ gnome_shell_extension_item.0 }}"
    gnome_shell_extension: "{{ gnome_shell_extension_item.1 }}"
    gnome_shell_extension_checkout_path: "/home/{{ gnome_shell_extension_item.0 }}/{{ gnome_shell_extension_cache_directory }}/{{ gnome_shell_extension_item.1.uuid }}"
    gnome_shell_extension_source_suffix: "{{ '/' ~ gnome_shell_extension_item.1.source_subdirectory if gnome_shell_extension_item.1.source_subdirectory | length > 0 else '' }}"
    gnome_shell_extension_source_path: "{{ gnome_shell_extension_checkout_path }}{{ gnome_shell_extension_source_suffix }}"
    gnome_shell_extension_install_path: "/home/{{ gnome_shell_extension_item.0 }}/{{ gnome_shell_extension_directory }}/{{ gnome_shell_extension_item.1.uuid }}"
  loop: "{{ gnome_desktop_users | product(gnome_shell_extension_sources) | list }}"
  loop_control:
    loop_var: gnome_shell_extension_item
    label: "{{ gnome_shell_extension_item.0 }} {{ gnome_shell_extension_item.1.name }}"
