---
- name: Provision Debian workstation
  hosts: workstations
  become: true
  gather_facts: true

  roles:
    - role: system_management
      vars:
        system_management_upgrade_packages: true
        system_management_upgrade_type: dist
        system_management_autoremove: true
        system_management_autoclean: true
        system_management_reboot_if_required: false
    - role: base
    - role: nvidia
    - role: spotify
    - role: gnome
    - role: workstation
    - role: productivity
    - role: dotfiles
    - role: neovim
    - role: bitwarden
    - role: deskflow
    - role: ai_cli
    - role: vscode
    - role: hashicorp
    - role: docker
    - role: virtualization
